### PR TITLE
Adapts api configuration to connect vite and flask

### PR DESCRIPTION
**Pull request by mwittep**
To resolve the problem that the app is not working in my case, I adapted the config file of vite and adapted the backend as well as the front end calls. 

@reviewers, could you test it and see if it is still working on your side?

### CODE REVIEW

**Review by Jenniksen — APPROVED** [review]
I tested the changes locally, and everything worked fine on my end.

**Comment by MarkusHenkel** [comment]
I tested the changes locally and the hotfix works. I did not receive the CORS policy error.

**Review by MarkusHenkel — APPROVED** [review]
I tested the changes locally and the hotfix works. I did not receive the CORS policy error.

**Comment by mwittep** [comment]
@MarkusHenkel @Jenniksen Great! Feel free to merge and adapt your implementation.

**Comment by Julian-Borbeck** [comment]
LGTM

**Review by Julian-Borbeck — COMMENTED** [review]
Tested it locally, works on my machine. Communication of backend and frontend also works

**Pull request closed without merging**
